#
# Copyright (C) 2026 The OrangeFox Recovery Project
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/xiaomi/air

ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true

# --- Target Architecture & Platform ---
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55
TARGET_BOARD_PLATFORM := mt6835

# --- 32-bit Companion Architecture ---
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

# --- Bootloader & Target Assertions ---
TARGET_BOOTLOADER_BOARD_NAME := air
TARGET_NO_BOOTLOADER := true
TARGET_OTA_ASSERT_DEVICE := air
TARGET_BOARD_INFO_FILE := $(DEVICE_PATH)/board-info.txt

# --- Kernel handling (use prebuilt, don't try to compile) ---
TARGET_NO_KERNEL_OVERRIDE := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel

# --- Recovery Boot Mode ---
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
TARGET_USES_MKE2FS := true
BOARD_USES_METADATA_PARTITION := true
BOARD_HAS_LARGE_FILESYSTEM := true

# --- Confirmed partition sizes ---
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_DTBOIMG_PARTITION_SIZE := 8388608

# --- Prebuilt DTBO ---
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_INCLUDE_RECOVERY_DTBO := true

# --- Prebuilt DTB (used inside vendor_boot) ---
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt
BOARD_MKBOOTIMG_ARGS += --dtb $(BOARD_PREBUILT_DTBIMAGE_DIR)/mt6835.dtb

# --- Boot Image Header Version ---
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_PAGESIZE := 4096

# --- Android 15 / HyperOS 2 Version & Platform Flags ---
PLATFORM_VERSION := 15
PLATFORM_SECURITY_PATCH := 2024-08-01

# --- A/B & Virtual A/B Partition Layout ---
AB_OTA_UPDATER := true
BOARD_USES_AB_IMAGE := true
BOARD_SUPER_PARTITION_BLOCK_DEVICES := super
BOARD_SUPER_PARTITION_GROUPS := air_dynamic_partitions
AB_OTA_PARTITIONS += boot system system_ext vendor product odm vendor_dlkm vendor_boot dtbo vbmeta

# --- Dynamic Partition Sizing ---
BOARD_SUPER_PARTITION_SIZE := 7516192768
BOARD_AIR_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext vendor product odm vendor_dlkm
BOARD_AIR_DYNAMIC_PARTITIONS_SIZE := 7511998464

# --- Partition Copy-Out Paths ---
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

# --- File System Types ---
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs

# --- Encryption & Crypto (FBE v2) ---
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2
TW_PREPARE_DATA_MEDIA_EARLY := true

# --- Display & UI Configuration ---
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1600
TARGET_SCREEN_DENSITY := 320
TW_THEME := portrait_hdpi
TW_Y_OFFSET := 0
TW_H_OFFSET := 0
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1200
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"

# --- Recovery Features & Flashing Safety ---
TW_INCLUDE_FASTBOOTD := true
FOX_VIRTUAL_AB_DEVICE := 1
FOX_VENDOR_BOOT_RECOVERY := 1
BOARD_AVB_ENABLE := true
TW_DISABLE_ALLOW_AVB_KEY_MISMATCH := false
TW_INCLUDE_REPACKTOOLS := true
TW_USE_TOOLBOX := true

# --- AVB Signing ---
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 0
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# --- OrangeFox specific variables ---
OF_MAINTAINER := Yash
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
FOX_ASH_IS_BASH := 1
OF_USE_MAGISKBOOT := 1
OF_FBE_METADATA_MOUNT_IGNORE := 1
