#
# Copyright (C) 2026 The OrangeFox Recovery Project
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/xiaomi/air

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true

# --- Target Architecture & Platform ---
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55
TARGET_BOARD_PLATFORM := mt6835

# --- 32-bit Companion Architecture (Optional Compatibility) ---
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

# --- Bootloader & Target Assertions ---
TARGET_BOOTLOADER_BOARD_NAME := air
TARGET_NO_BOOTLOADER := true
TARGET_OTA_ASSERT_DEVICE := air

# --- Recovery Boot Mode & Mounts ---
BOARD_USES_RECOVERY_AS_BOOT := false
TARGET_USES_MKE2FS := true
BOARD_USES_METADATA_PARTITION := true
BOARD_HAS_LARGE_FILESYSTEM := true

# --- Prebuilt Kernel & Device Tree Paths ---
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/vendor_boot.img-kernel
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img

# --- Boot Image Header & Kernel Parameters (MT6835 GKI 2.0) ---
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_KERNEL_TAGS_OFFSET := 0x07c88000
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

# --- Android 15 / HyperOS 2 Version & Platform Flags ---
PLATFORM_VERSION := 15
PLATFORM_SECURITY_PATCH := 2024-08-01
BOARD_SYSTEMSDK_VERSIONS := 35

# --- A/B & Virtual A/B Partition Layout ---
AB_OTA_UPDATER := true
BOARD_USES_AB_IMAGE := true
BOARD_SUPER_PARTITION_BLOCK_DEVICES := super
BOARD_SUPER_PARTITION_GROUPS := air_dynamic_partitions

# --- Dynamic Partition Sizing ---
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_AIR_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext vendor product odm vendor_dlkm
BOARD_AIR_DYNAMIC_PARTITIONS_SIZE := 9122611200

# --- File System Types ---
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIIMAGE_FILE_SYSTEM_TYPE := ext4

# --- Encryption & Crypto (FBE v2) ---
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2
TW_PREPARE_DATA_MEDIA_EARLY := true

# --- Display & UI Configuration ---
TARGET_SCREEN_DENSITY := 320
TW_THEME := portrait_vhd
TW_Y_OFFSET := 0
TW_H_OFFSET := 0

# --- Recovery Features & Flashing Safety ---
TW_INCLUDE_FASTBOOTD := true
FOX_VIRTUAL_AB_DEVICE := 1
BOARD_AVB_ENABLE := true
TW_DISABLE_ALLOW_AVB_KEY_MISMATCH := false
TW_INCLUDE_REPACKTOOLS := true
TW_USE_TOOLBOX := true
